import type { NextApiRequest, NextApiResponse } from "next";
import nodemailer from "nodemailer";
import { verifyRecaptcha } from "./utils/verifyRecaptcha";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { mobileNumber, recaptchaToken } = req.body;

  if (!mobileNumber) {
    return res.status(400).json({ error: "Mobile number is required" });
  }
  if (!recaptchaToken) {
    return res.status(400).json({ error: "Captcha token missing" });
  }

  const captchaResult = await verifyRecaptcha(recaptchaToken);
  if (!captchaResult.success) {
    return res.status(400).json({ error: captchaResult.error || "Captcha verification failed. Please try again." });
  }

  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: process.env.EMAIL_RECEIVER,
      subject: "📰 New Free Consultation Request - Skillup Study Abroad",
      html: `
    <div style="font-family: Arial, sans-serif; color: #333; padding: 20px;">
      <h2 style="color: #030303; margin-bottom: 10px;">New Free Consultation Request</h2>
      <p style="font-size: 16px; margin: 8px 0;">A new user has requested a free consultation.</p>

      <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 12px 0; border: 1px solid #e0e0e0; width: fit-content;">
        <p style="margin: 0;"><strong>Mobile Number:</strong> ${mobileNumber}</p>
      </div>

      <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
      <p style="font-size: 12px; color: #777;">
        This message was automatically generated by the Skillup Study Abroad website.
      </p>
    </div>
  `,
    };

    await transporter.sendMail(mailOptions);
    return res
      .status(200)
      .json({ message: "Free consultation request sent successfully" });
  } catch (error) {
    console.error("Error sending free consultation request email:", error);
    return res.status(500).json({ error: "Failed to send free consultation request email" });
  }
}
