import type { NextApiRequest, NextApiResponse } from "next";
import nodemailer from "nodemailer";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { email } = req.body;

  if (!email) {
    return res.status(400).json({ error: "Email is required" });
  }

  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    });

    const mailOptions = {
      from: process.env.GMAIL_USER,
      to: process.env.GMAIL_RECEIVER,
      subject: "📰 New Newsletter Subscription - Skillup Study Abroad",
      html: `
    <div style="font-family: Arial, sans-serif; color: #333; padding: 20px;">
      <h2 style="color: #030303; margin-bottom: 10px;">New Newsletter Subscription</h2>
      <p style="font-size: 16px; margin: 8px 0;">A new user has subscribed to your newsletter.</p>
      
      <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 12px 0; border: 1px solid #e0e0e0; width: fit-content;">
        <p style="margin: 0;"><strong>Email:</strong> ${email}</p>
      </div>

      <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
      <p style="font-size: 12px; color: #777;">
        This message was automatically generated by the Skillup Study Abroad website.
      </p>
    </div>
  `,
    };

    await transporter.sendMail(mailOptions);
    return res
      .status(200)
      .json({ message: "Subscription email sent successfully" });
  } catch (error) {
    console.error("Error sending subscription email:", error);
    return res.status(500).json({ error: "Failed to send subscription email" });
  }
}
